In [1]:
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd
import time
import re
import numpy as np
import time

In [2]:
df = pd.DataFrame({"Home Team": [-1] * 1000, "Away Team": [-1] * 1000, "Home Score": [-1] * 1000, "Away Score": [-1] * 1000})

In [3]:
### 5~8월 kbo 경기 결과 크롤링

# 데이터를 저장할 데이터프레임
df = pd.DataFrame({"Date": [None] * 10000, "Home": [None] * 10000, "Away": [None] * 10000, "H_Score": [None] * 10000, 
                   "A_Score": [None] * 10000, "H_Pitcher": [None] * 10000, "A_Pitcher": [None] * 10000,
                  "is_canceled": [None] * 10000})


URL = "https://www.koreabaseball.com/ws/Main.asmx/GetKboGameList"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
    "Referer": "https://www.koreabaseball.com/Schedule/GameCenter/Main.aspx"
}


# 정규표현식
game_date_pattern = re.compile("G_DT\D:\D\D(?P<date>[\d]+)")
home_name_pattern = re.compile("HOME_NM\D\D\D\D(?P<name>[\w]+)")
away_name_pattern = re.compile("AWAY_NM\D\D\D\D(?P<name>[\w]+)")
home_score_pattern = re.compile("B_SCORE_CN\D\D\D\D(?P<score>[\d]+)")
away_score_pattern = re.compile("T_SCORE_CN\D\D\D\D(?P<score>[\d]+)")
win_pitcher_pattern = re.compile("W_PIT_P_NM\D\D\D\D(?P<name>[\w]+)")
lost_pitcher_pattern = re.compile("L_PIT_P_NM\D\D\D\D(?P<name>[\w]+)")
is_canceled_pattern = re.compile("CANCEL_SC_ID\D\D\D\D(?P<name>[\w]+)")

home_pitcher_pattern = re.compile("B_PIT_P_NM\D\D\D\D(?P<name>[\w]+)")
away_pitcher_pattern = re.compile("T_PIT_P_NM\D\D\D\D(?P<name>[\w]+)")


index = 0
for month in [5,6,7,8]:
    
    for day in range(1,32):

        if day<10:
            date = "0"+str(day)
        else:
            date= day 

        form_data = {
            "leId": 1,
            "srId": "0,1,3,4,5,7,8,9",
            "date": "20200{}{}".format(month, date)
        }

        res = req.post(url=URL, headers=headers, data=form_data)
        soup = bs(res.text, "html.parser")

        # 데이터
        dates = re.findall(game_date_pattern, str(soup))
        home_names = re.findall(home_name_pattern, str(soup))
        away_names = re.findall(away_name_pattern, str(soup))
        home_scores = re.findall(home_score_pattern, str(soup))
        away_scores = re.findall(away_score_pattern, str(soup))
        # win_pitchers = re.findall(win_pitcher_pattern, str(soup))
        # lost_pitchers = re.findall(lost_pitcher_pattern, str(soup))
        is_canceled = re.findall(is_canceled_pattern, str(soup))
        
        home_pitchers = re.findall(home_pitcher_pattern, str(soup))
        away_pitchers = re.findall(away_pitcher_pattern, str(soup))

        for i in range(len(dates)):
            
            # 취소된 경기:
            if is_canceled[i] == "1":
                df.iloc[i+index, 0] = dates[i]
                df.iloc[i+index, 1] = home_names[i]
                df.iloc[i+index, 2] = away_names[i]
                df.iloc[i+index, 3:7] = "Canceled"
                df.iloc[i+index, 7] = "Yes"
            
            # 정상 경기
            elif is_canceled[i] == "0":
                df.iloc[i+index, 0] = dates[i]
                df.iloc[i+index, 1] = home_names[i]
                df.iloc[i+index, 2] = away_names[i]
                df.iloc[i+index, 3] = int(home_scores[i])
                df.iloc[i+index, 4] = int(away_scores[i])

                if home_scores[i] == away_scores[i]:  # 비긴 경우
                    print("{}: {} vs {} 은 무승부경기입니다.".format(dates[i], home_names[i], away_names[i]))
                    df.iloc[i+index, 5] = home_pitchers[i]
                    df.iloc[i+index, 6] = away_pitchers[i]

                else:
                    df.iloc[i+index, 5] = home_pitchers[i]
                    df.iloc[i+index, 6] = away_pitchers[i]
                
                df.iloc[i+index, 7] = "No"
                
            
            else:
                print("Unknown Error")


        index += 5

        time.sleep(3)
        print("{}경기 크롤링 완료".format(df.iloc[index-1, 0]))

None경기 크롤링 완료
None경기 크롤링 완료
None경기 크롤링 완료
None경기 크롤링 완료
20200505경기 크롤링 완료
20200506경기 크롤링 완료
20200507경기 크롤링 완료
20200508경기 크롤링 완료
20200509경기 크롤링 완료
20200510경기 크롤링 완료
None경기 크롤링 완료
20200512경기 크롤링 완료
20200513경기 크롤링 완료
20200514경기 크롤링 완료
20200515경기 크롤링 완료
20200516경기 크롤링 완료
20200517경기 크롤링 완료
None경기 크롤링 완료
20200519경기 크롤링 완료
20200520경기 크롤링 완료
20200521경기 크롤링 완료
20200522경기 크롤링 완료
20200523경기 크롤링 완료
20200524경기 크롤링 완료
None경기 크롤링 완료
20200526경기 크롤링 완료
20200527경기 크롤링 완료
20200528경기 크롤링 완료
20200529경기 크롤링 완료
20200530경기 크롤링 완료
20200531경기 크롤링 완료
None경기 크롤링 완료
20200602경기 크롤링 완료
20200603경기 크롤링 완료
20200604경기 크롤링 완료
20200605경기 크롤링 완료
20200606경기 크롤링 완료
20200607경기 크롤링 완료
None경기 크롤링 완료
20200609경기 크롤링 완료
20200610경기 크롤링 완료
20200611경기 크롤링 완료
20200612경기 크롤링 완료
20200613경기 크롤링 완료
20200614경기 크롤링 완료
None경기 크롤링 완료
20200616경기 크롤링 완료
20200617경기 크롤링 완료
20200618경기 크롤링 완료
20200619경기 크롤링 완료
20200620경기 크롤링 완료
20200621경기 크롤링 완료
None경기 크롤링 완료
20200623경기 크롤링 완료
20200624경기 크롤링 완료
20200625경기 크롤링 완료
20200626경기 크롤링 완료
20200627경기 크롤링 완료
20200628경기 크롤링 완료
None경기 크롤링 완료
20200630경기 크롤링 완료
None경기 크롤링 완료
20200701경기 크롤링 완료
20200702경기 크롤링 완료
20200703경기 크롤링 완료
20200704경기 크롤링 완료
20200705경기 크롤링 완료
None경기 크롤링 완료
20200707경기 크롤링 완료
20200708경기 크롤링 완료
20200709경기 크롤링 완료
20200710경기 크롤링 완료
20200711: LG vs NC 은 무승부경기입니다.
20200711경기 크롤링 완료
20200712경기 크롤링 완료
20200713경기 크롤링 완료
20200714경기 크롤링 완료
20200715경기 크롤링 완료
20200716경기 크롤링 완료
20200717: NC vs KT 은 무승부경기입니다.
20200717경기 크롤링 완료
20200718경기 크롤링 완료
20200719경기 크롤링 완료
None경기 크롤링 완료
20200721경기 크롤링 완료
Unknown Error
20200722경기 크롤링 완료
20200723경기 크롤링 완료
20200724경기 크롤링 완료
20200725경기 크롤링 완료
20200726경기 크롤링 완료
20200727: 한화 vs SK 은 무승부경기입니다.
None경기 크롤링 완료
20200728경기 크롤링 완료
20200729경기 크롤링 완료
20200730경기 크롤링 완료
20200731경기 크롤링 완료
20200801경기 크롤링 완료
20200802경기 크롤링 완료
None경기 크롤링 완료
20200804경기 크롤링 완료
20200805: 두산 vs 삼성 은 무승부경기입니다.
20200805경기 크롤링 완료
20200806경기 크롤링 완료
20200807경기 크롤링 완료
20200808: 두산 vs 롯데 은 무승부경기입니다.
20200808경기 크롤링 완료
20200809경기 크롤링 완료
None경기 크롤링 완료
20200811경기 크롤링 완료
20200812경기 크롤링 완료
20200813경기 크롤링 완료
20200814경기 크롤링 완료
20200815경기 크롤링 완료
20200816경기 크롤링 완료
None경기 크롤링 완료
20200818경기 크롤링 완료
20200819경기 크롤링 완료
20200820경기 크롤링 완료
20200821경기 크롤링 완료
20200822경기 크롤링 완료
20200823경기 크롤링 완료
None경기 크롤링 완료
20200825경기 크롤링 완료
20200826경기 크롤링 완료
20200827경기 크롤링 완료
20200828경기 크롤링 완료
20200829: LG vs 두산 은 무승부경기입니다.
20200829경기 크롤링 완료
20200830경기 크롤링 완료
None경기 크롤링 완료

In [4]:
df = df.dropna().reset_index().drop("index", axis=1)

In [5]:
df

         Date Home Away H_Score A_Score H_Pitcher A_Pitcher is_canceled
0    20200505   LG   두산       8       2       차우찬      알칸타라          No
1    20200505   SK   한화       0       3        킹엄       서폴드          No
2    20200505   삼성   NC       0       4       백정현      루친스키          No
3    20200505   KT   롯데       2       7     데스파이네     스트레일리          No
4    20200505  KIA   키움       2      11       양현종       브리검          No
..        ...  ...  ...     ...     ...       ...       ...         ...
518  20200830   롯데   한화       6       2        샘슨       서폴드          No
519  20200830   NC   SK       7       4       신민혁       이건욱          No
520  20200830   키움   삼성       3       2       브리검      라이블리          No
521  20200830  KIA   KT       5       8       김기훈     데스파이네          No
522  20200830  KIA   KT       7       5       이민우      쿠에바스          No

[523 rows x 8 columns]

In [6]:
df.head()

       Date Home Away H_Score A_Score H_Pitcher A_Pitcher is_canceled
0  20200505   LG   두산       8       2       차우찬      알칸타라          No
1  20200505   SK   한화       0       3        킹엄       서폴드          No
2  20200505   삼성   NC       0       4       백정현      루친스키          No
3  20200505   KT   롯데       2       7     데스파이네     스트레일리          No
4  20200505  KIA   키움       2      11       양현종       브리검          No

In [17]:
# 데이터 저장
df.to_csv("./2020KBO.csv")